CONDA_BUILD_SYSROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk
c_compiler: clang
c_compiler_version: '17'
c_stdlib: macosx_deployment_target
c_stdlib_version: '12.1'
channel_targets: defaults
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cross_target_platform: osx-arm64
cxx_compiler: clangxx
cxx_compiler_version: '17'
extend_keys:
- pin_run_as_build
- extend_keys
- ignore_build_only_deps
- ignore_version
fortran_compiler: gfortran
gfortran_maj_ver: '15'
gfortran_version: 15.2.0
gmp: 6.3.0
ignore_build_only_deps:
- python
- numpy
isl: '0.22'
libgfortran_soversion: '5'
libiconv: '1'
lua: '5'
macos_machine: arm64-apple-darwin20.0.0
mpc: '1'
mpfr: '4'
numpy: '1.26'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
platform: osx-arm64
python: '3.12'
r_base: '3.5'
target_platform: osx-arm64
zip_keys:
- - cross_target_platform
  - macos_machine
- - gfortran_version
  - gfortran_maj_ver
  - libgfortran_soversion
zlib: '1.2'
